[package]
name = "metro"
version = "0.1.0"
authors = ["welien"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
ndarray = "0.13.1"
itertools = "0.9.0"
crossbeam = "0.7"
